server:
  port: 9090
  
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: system
    password: abhigya
    driver-class-name: oracle.jdbc.driver.OracleDriver
  
  jpa:
    properties:
      hibernate:
        show_sql:true
        format_sql:true
    hibernate:
      ddl-auto: update      
   
  mail:
    host: smtp.gmail.com
    port: 587
    username: sableashwini707@gmail.com
    password: Nilesh@90
    properties:
      mail:
       smtp:
        starttls:
          enable:true
         auth:true      
app:
  messages:
     invalidCredentials: Credentials are Invalid
     accountLocked: Your account is locked
     regSuccess: Registration almost completed.Please check your email to proceed.      
     unlockSucc: Your Account unlocked successfully
     unlockFail: Fail to unlocked account
     regEmailSub: User Registration Successfull | User
     forgotPwdEmailSub: Forgot Password | User
     forgotPwdSuccess: Email sent with password
     forgotPwdFail: Enter correct Email Id
     regMailBodyFile: UNLOCK-ACC-EMAIL-BODY-TEMPLATE.txt
     forgotPwdMailBodyFile: RECOVER-PASSWORD-EMAIL-BODY-TEMPLATE.txt